{block content}
    <hr class="clear" />
    <div id="cancel-send">
        <p><strong>{_'Objednávka nebyla úspěšně dokončena '}</strong></p>
    </div>
    <div id="succes-div">
        <h3>{_'Tvoje platba bohužel neproběhla úspěšně.'}</h3>
        <ul>
            <li>{_'Platba byla zamítnuta ze strany poskytovatele platební služby'}.</li>
            <li>{_'Co nejdříve tě budeme kontaktovat, abych vše vyřešili ke tvé spokojenosti.'}.</li>
            <li>{_'Děkujeme za tvou objednávku'}.</li>
        </ul>
    </div>
    <a id="toShop" href="{plink Default:}"></a>
    <hr class='clear' />
{/block}