{block content}
    <div id="succes-send">
        <p>{_'Objednávka byla úspěšně'} <strong>{_'dokončena'}.</strong></p>
    </div>
    <div id="succes-div">
        <h3>{_'Objednávka odeslána'}</h3>
        <ul>
            <li>{_'Vaše objednávka byla odeslána k vyřízení'}.</li>
            <li>{_'O stavu vaší objednávky vás budeme informovat emailem'}.</li>
            <li>{_'Potvrzení o přijetí objednávky vám zasíláme zároveň i na váš e-mail'}.</li>
        </ul>
    </div>
    <a id="toShop" href="{plink Default:}"></a>
    <hr class="clear" />
{/block}