{block presenter}user account{/block}
{block content}
    {* <!-- ********************************************************************** --> *}
    {* <!-- ******************** USER (sprava uctu uzivatele) ******************** --> *}
    {* <!--                                                                        --> *}
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            {* <!-- ******************** MENU ******************** --> *}
            {* <!-- ______________________________________________ --> *}
            <div class="user-menu">
                <h1>{_('Můj účet')}</h1><strong>{$user->name} {$user->surname}</strong>
                <a class="logout" n:href="logout!">{_'Odhlásit se'}</a>
                <hr class="divider-big">
                <ul class="main-user-nav">
                    <li class="osobni active"><a href="{plink Users:account}">{_'Osobní sekce'}</a></li>
                    <li class="objednavky"><a href="{plink Users:orders}">{_'Objednávky'}</a></li>
                    <li class="seznam">
                        {snippet userinteractionwishuser}
                            {if isset($user->id)}
                                <span class="count">{$wishlistCount}</span>
                                <a n:href="Wishlist:detail $wishlist->id">{_'Můj seznam'}</a>
                            {else}
                                <a href="{plink Wishlist:default}">{_'Můj seznam'}</a></li>
                            {/if}
                        {/snippet}
                    <li class="navrhy"><a href="{plink Users:sendmsg}" class="send-us">{_'Přání a návrhy'}</a></li>
                </ul>
                <ul class="secondary-user-nav">
                    <li><a href="{plink Users:personalize}">{_'Personalizace'}</a></li>
                    <li class="active"><a href="{plink Users:account}">{_'Změnit osobní údaje'}</a></li>
                    <li><a href="{plink Users:changepassword}">{_'Změnit heslo'}</a></li>
                </ul>
            </div>
            {* <!-- ******************** CONTENT ******************** --> *}
            {* <!-- _________________________________________________ --> *}
            <div class="user-content">
                {control editUserForm}
                <!--
                <div class="clear divider-big"></div>
                {if isset($orders) && count($orders)>0}
                    <table id="basket-table">
                        <tr class="basket-table-head">
                            <th>{_('Číslo')}</th><th>{_('Datum')}</th><th>{_'Cena'}</th></tr>
                        
                        {foreach $orders as $item}
                            <tr class="orders {if $iterator->getCounter()%2 == 0}even{/if}">
                                <td><strong>{$item->order_number}</strong></td>
                                <td>{$item->date_ordered|date:'%d. %m. %Y'} ({? $a = Order::getStatusArray()}{$a[$item->status]})</td>
                                <td><b>{$item->totalAmount|money}</b></td>
                            </tr>
                                {foreach $item->products as $product}
                                    <tr class="order-products {if $iterator->getCounter()%2 == 0}even{/if}">
                                        <td>{$product->count}x</td>
                                        <td><a href="{plink Detail:default $product->id}">{$product->name}</a></td>
                                        <td>á {$product->price|money_czk:2} Kč</td>
                                    </tr>
                                {/foreach}
                        {/foreach}
                    </table>
                {else}
                    <p>{_'Žádné objednávky nebyly odeslány skrze tento účet'}.</p>
                {/if}
                <div class="clear divider-big"></div>
                -->
            </div>
        </div>
    </div>
    <script>
        $('tr.orders').click(function(){
            $(this).addClass('open')
            $('tr.orders.open .order-products').fadeIn();
        });
    </script>
{/block}
