{block presenter}user sendpassword{/block}
{block content}
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            <h2>{_('Zaslat ztracené heslo')}</h2>
            {if isset($flashes[0])}<p class="flash {$flashes[0]->type}">{$flashes[0]->message}</p>{/if}
            <p>{_'Po vyplnění tohoto formuláře vám bude zasláno vaše nové heslo.'}</p>
            <hr class="clear" />
            <div class="newuser">
                {control sendPassForm}
            </div>
        </div>
    </div>     
{/block}