{block presenter}wishlist{/block}
{block content}
    {* <!-- ********************************************************************** --> *}
    {* <!-- ******************** USER (sprava uctu uzivatele) ******************** --> *}
    {* <!--                                                                        --> *}
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            {* <!-- ******************** MENU ******************** --> *}
            {* <!-- ______________________________________________ --> *}
            <div class="user-menu">
                <h1>{_('Můj účet')}</h1><strong>{$user->name} {$user->surname}</strong>
                <a class="logout" n:href="logout!">{_'Odhlásit se'}</a>
                <hr class="divider-big">
                <ul class="main-user-nav">
                    <li class="osobni"><a href="{plink Users:account}">{_'Osobní sekce'}</i></a></li>
                    <li class="objednavky"><a href="{plink Users:orders}">{_'Objednávky'}</a></li>
                    <li class="seznam active">
                        {snippet userinteractionwishuser}
                            {if isset($user->id)}
                                <span class="count">{count($wishlist->getItems())}</span>
                                <a n:href="Wishlist:detail $wishlist->id" >{_'Můj seznam'}</a>
                            {else}
                                <a href="{plink Wishlist:default}">{_'Můj seznam'}</a></li>
                            {/if}
                        {/snippet}
                    <li class="navrhy"><a href="{plink Users:sendmsg}" class="send-us">{_'Přání a návrhy'}</a></li>
                </ul>
            </div>
            {* <!-- ******************** CONTENT ******************** --> *}
            {* <!-- _________________________________________________ --> *}
            <div class="user-content">
                <span>Seřadit dle</span>
                <ul class="sort-by">
                    <li class="sort active" data-sort="default" data-order="asc">Data přidání</li>
                    <li class="sort" data-sort="data-price" data-order="desc">Od nejlevnějšího</li>
                    <li class="sort" data-sort="data-price" data-order="asc">Od nejdražšího</li>
                    <li class="sort" data-sort="data-name" data-order="desc">Názvu A-Z</li>
                    <li class="sort" data-sort="data-name" data-order="asc">Názvu Z-A</li>
                </ul>
                <hr class="clear" />
                <div id="wish-list">
                    <ul class="row ul products-list" n:snippet="">
                    {foreach $wishlist->items as $item}
                        {include ../Includes/product-list-wishlist.phtml item=>$item}
                    {/foreach}
                    </ul>
                    
                    <hr />
                    <script>
                        //checkbox
                        $('.search-box .check').live('click',function(){
                            if ( $(this).hasClass("ac") ) {
                                $(this).removeClass('ac');
                            }else{
                                $(this).addClass('ac');
                            }
                        });
                    </script>
                </div>
            </div>
        </div>
    </div>
{/block}