
{block canonical}
    {if isset($actualCategory)}
    <link rel="canonical" href="{plink //Search:default 'limiter'=>array('category'=>$actualCategory->id)}"/>
    {/if}
{/block}
{block presenter}search{/block}

{block banner}
{if isset($actualCategory)}
    {foreach $actualCategory->galleries as $gall}
        {if $gall->implementation_name == 'banner'}
            {foreach $gall->files as $file}        
                <div class="cat-banner">
                    <img src="{plink Files:default $file->id,1170,125}" alt="" class="img-responsive cat-img-banner" />
                </div>
            {/foreach}
{* <img src="" data-src="holder.js/100%x120/text:Banner(výpis produktů)" class="test img-rounded img-responsive" /> *}
        {/if}
    {/foreach}
    {/if}
{/block}

{block content}
  
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">


            {* <!-- ********************************************************************************* --> *}
            {* <!-- ******************** PRODUCT-LIST (výpis produktů kategorie) ******************** --> *}
            {* <!--                                                                                   --> *}
            {if isset($limiter["category_list"]) && $limiter["category_list"] == '2'}
                <p>test hudba</p>
                {? var_dump('$actualCategory');}
            {/if}
            {if isset($limiter["gender"]) && $limiter["gender"] == '23'}
                <p>test muži</p>
                {? var_dump('$actualCategory');}
            {else if}
                <p>ženyz</p>
            {/if}

            {if isset($actualCategory) && $actualCategory->id != 4 && $actualCategory->id != 5}
                <div class="row products">
                    {* <!-- ******************** L - LEVY SLOUPEC (filtr) ******************** --> *}
                    {* <!-- __________________________________________________________________ --> *}
                    <div class="col-xs-2 col-sm-2 col-md-2 col-lg-2">
                        <div class="row">
                        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 left-filter">
                            <h2 class="filter-heading">Můj výběr</h2>
                            <hr class="divider-sml line" />
                            {include ../Includes/filter.phtml limitersURL => $limitersURL}
                        </div>
                    </div>
                    </div>
                    {* <!-- ******************** R - PRAVY SLOUPEC (vypis kategorie) ******************** --> *}
                    {* <!-- _____________________________________________________________________________ --> *}
                    <div class="col-xs-10 col-sm-10 col-md-10 col-lg-10">
                        {control breadcrumb}
                            <div class="cat-description">
                            {foreach $actualCategory->galleries as $gal}
                                {foreach $gal->files as $file}    
                                    {if $gal->implementation_name == 'uvodni'}    
                                        {if isset($file->url) && $file->url != '' }
                                            {if strpos($file->url , 'youtube')}
                                                <object width="459" height="258" class="youtube">
                                                    <param value="true" name="allowfullscreen" />
                                                    <param value="always" name="allowscriptaccess" />
                                                    <param name="movie" value="{$file->url|replace:'watch?v=':'v/'}?version=3&amp;hl=cs_CZ" />
                                                    <param name="wmode" value="transparent" />
                                                    <embed width="459" height="258" allowscriptaccess="always" 
                                                      allowfullscreen="true" type="application/x-shockwave-flash"          
                                                      src="{$file->url|replace:'watch?v=':'v/'}?version=3&amp;hl=cs_CZ"
                                                      wmode="transparent"
                                                      >
                                                    </embed>
                                                </object>
                                            {elseif strpos($file->url , 'vimeo')}
                                                <iframe  class="vimeo" src="{$file->url|replace:'http://vimeo.com/':'//player.vimeo.com/video/'}?title=0&amp;byline=0&amp;portrait=0&amp;badge=0&amp;color=ffffff" width="459" height="258" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
                                            {/if}                                        
                                        {else}
                                            <img src="{plink Files:default $file->id,459,258,null,null,false,File::FILL}" class="img-thumbnail pull-left" />
                                        {/if}
                                    {/if}
                                {/foreach}                                
                            {/foreach}
                            <h1>{if isset($actualCategory)}{$actualCategory->title}{else}{_'Výsledky vyhledávání'}{/if}</h1>
                            <div>{if isset($actualCategory)}{!$actualCategory->description|truncate:530}{/if}</div>
                            <hr class="clear" />
                        </div>
                       
                        {* <!-- CO FRCI (slider) --> *}
                        {if isset($lists['co-frci']) && count($lists['co-frci'])>=5}    
                        <div class="row" id="gal-wrap-frci">
                            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">                
                                <h2 class="endlessgal">Co právě frčí (cat)</h2>
                                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 co-frci" id="co-prave-frci"> 
                                    <ul class="row ul products-list">                                    
                                        {foreach $lists['co-frci'] as $product}
                                            <li class="col-xs-2 col-sm-2 col-md-2 col-lg-2 {if $iterator->getCounter()%5==0}last{/if}">
                                                {include ../Includes/product-list.phtml product=>$product}
                                            </li>
                                        {/foreach}
                                        <div class="clear"></div>
                                    </ul>
                                </div>
                                <script>
                                    $('#co-prave-frci').endlessGallery({ speed: 200, count: 1 });
                                    $('#out-co-prave-frci').addClass('row');
                                </script>
                            </div>
                        </div>
                        {/if}
                        <div id="ordererTabs"></div>
                        {* <!-- ******************** PRODUCT-LIST ******************** --> *}
                        {snippet productsList}
                            <ul class="row" id="products-list">
                                {foreach $productsList as $product}    
                                    <li class="col-xs-2 col-sm-2 col-md-2 col-lg-2 {if $iterator->getCounter()%5==0}last{/if}">
                                        {include ../Includes/product-list.phtml product=>$product}
                                    </li>
                                {/foreach}
                                {if !isset($user)}
                                    <script>
                                        $('.to-wish').click(function(){
                                            alert('Pro vložení prouktu do nákupního seznamu je nutné se přihlásit.')
                                            $("html:not(:animated),body:not(:animated)").animate({ scrollTop: $("body").offset().top }, 300 );
                                            $('#snippet-simpleLoginForm-simpleloginlogin a.simple-login-login').trigger('click');
                                            $('#frm-simpleLoginForm-loginForm #frmloginForm-login.text').focus();
                                            return false;
                                        });
                                    </script>
                                {else}

                                {/if}
                            </ul>
                        {/snippet}
                        {widget paginator}
                        <script>
                            $(window).on('scroll',function(){
                                if($(window).scrollTop() + $(window).height() > $(document).height() - 1000) {
                                    if ($('a.next').length>0){
                                        $('a.paginator-next-button').trigger('click');
                                    }
                                    else {
                                        $('#gal-wrap-note').fadeIn();
                                    }
                                }
                            });        
                        </script>                         

                        {* <!-- CO FRCI (slider) --> *}
                    {* <!-- <script>
                            $(window).scroll(function() {
                                if(isVisibleOnScreen($('#bott-list1'))) {
                                    $('#bott-list1').fadeIn();
                                }
                            });
                        </script> --> *}
                        <div class="row" id="gal-wrap-note">
                            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                                <h2 class="h-na-note">Na podobné notě</h2>
                                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 endless na-note" id="na-podobne-note"> 
                                    <ul class="row ul products-list">                                    
                                        {foreach $lists['co-frci'] as $product}
                                            <li class="col-xs-2 col-sm-2 col-md-2 col-lg-2 {if $iterator->getCounter()%5==0}last{/if}">
                                                {include ../Includes/product-list.phtml product=>$product}
                                            </li>
                                        {/foreach}
                                    </ul>
                                </div>
                                <script>
                                    $('#na-podobne-note').endlessGallery({ speed: 200, count: 1 });
                                    $('#out-na-podobne-note').addClass('row');
                                </script>
                                {*
                                    <div class="prev" ></div>
                                    <div class="next" ></div>
                                *}
                            </div>
                        </div>
                        <div class="divider-big"></div>
                        <a class="anchor">Nahoru</a>
                    </div>
                </div>

            
            {* <!-- ***************************************************************************** --> *}
            {* <!-- ******************** SEZNAMY INTERPRETŮ, UDÁLOSTÍ, VÝROBCŮ ******************** --> *}
            {* <!--                                                                               --> *}
            {else}

                {* <!-- ******************** SEZNAM INTERPRETŮ (vypis kategorií) ******************** --> *}
                {* <!-- _____________________________________________________________________________ --> *}
                {if isset($actualCategory) && ($actualCategory->hasList('hudba') || $actualCategory->hasList('film'))}
                cc
                    {* <!-- - - - - - - - - - --> *}
                    <div class="row lists">
                        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                            {* <!-- ******************** FILTR DLE ŽÁNRU ******************** --> *}
                            {if $actualCategory->id === 4}
                                <h1>A-Z Hudba</h1>
                                <div class="row check-filter">
                                    <div class="reset-check">
                                        <span class="heading">Žánry:</span><br />
                                        <span class="reset">Zrušit vše</span>
                                    </div>                            
                                    {if $actualCategory->id === 4}
                                        {? $implementationName = 'zanrhudba'; }
                                    {/if}
                                    {if $actualCategory->id === 5}
                                        {? $implementationName = 'zanrfilm'; }
                                    {/if}

                                    {? $sortedParams = array(); }

                                    {foreach $productsList as $product}
                                        {if isset($product->param[$implementationName]) && !empty($product->param[$implementationName])}
                                        
                                            {if is_array($product->param[$implementationName])}
                                                {? $params = $product->param[$implementationName]}
                                            {else}
                                                {? $params = array($product->param[$implementationName])}  {* produkt ma tento parametr pouze s jednou hodnotou (tzn nevraci to pole), tak si to pole vytvorime *}
                                            {/if}
                                        
                                            {foreach $params as $param}
                                                {if !array_key_exists($param->id, $sortedParams)}
                                                    {? $sortedParams[$param->id] = $param; }
                                                {/if}
                                            {/foreach}
                                        {/if}
                                    {/foreach}

                                    <?php
                                        function cmpParamName($a, $b){
                                            if ($a->name == $b->name) {
                                                return 0;
                                            }
                                            return ($a->name < $b->name) ? -1 : 1;
                                        }
                                    ?>
                                    {? usort($sortedParams, 'cmpParamName') }

                                    {foreach $sortedParams as $param}
                                        <div class="col-xs-2 col-sm-2 col-md-2 col-lg-2">
                                            <div class="checkbox">
                                                <label>
                                                    <input type="checkbox" value="">{$param->name}
                                                </label>
                                            </div>
                                        </div>
                                    {/foreach}
                                </div>
                                <div class="divider-big"></div>
                            {/if}
                            
                            {if $actualCategory->id === 4 }
                                {* ******************** TOP INTERPRETI () ******************** *}
                                <div class="row top-interprets">
                                    {foreach $actualCategory->getInnerCategories() as $cat2}
                                    {foreach $cat2->galleries as $gal}
                                        {if $gal->implementation_name == 'logo' && $gal->description == 'top'}
                                            {foreach $gal->files as $file}
                                            <div class="col-xs-2 col-sm-2 col-md-2 col-lg-2">
                                                <a href="{plink Search:default array('category'=>$cat2->id)}" class="">
                                                <img src="{plink Files:default $file->id,130,90,null,null,false,File::FILL}" class="img-responsive" /></a>
                                            </div>
                                            {/foreach}
                                        {/if}
                                    {/foreach}
                                    {/foreach}
                                </div>
                                <div class="divider-big"></div>
                            {/if}

                            {* <!-- ******************** ABECEDA INTERPRETŮ () ******************** --> *}

                            {?
                                $alphabet = array('a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z');
                            }
                            <div class="onlyforheight"></div>
                            <div class="row" id="fixed-alphabet">
                                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                                    <div class="btn-group btn-group-justified alphabet">
                                        {foreach $alphabet as $letter}
                                            <a data-href="#{$letter}" class="btn btn-default {$letter}">{$letter}</a>
                                        {/foreach}
                                    </div>                                 
                                </div>
                            </div>
                            <script>
                                function isVisibleOnScreen2(element) {
                                    var scrollToElem = $(window).scrollTop();
                                    return (scrollToElem > 590) ? true : false;
                                }
                                $(window).scroll(function() {
                                    if(isVisibleOnScreen2($('#fixed-alphabet'))) {     
                                        $('#fixed-alphabet').addClass('fixed-alphabet');
                                        $('.alphabet').addClass('alphabet-bdb')
                                        $('.onlyforheight').css('display','block')
                                       
                                    } else {                                       
                                        $('#fixed-alphabet').removeClass('fixed-alphabet');
                                        $('.alphabet').removeClass('alphabet-bdb')
                                        $('.onlyforheight').css('display','none')
                                    };  
                                });
                                
                            </script>
                            {* <!-- ******************** SEZNAM UDÁLOSTÍ (výpis parametrů) ******************** --> *}
                        {* <!--                                                                             --> *}

                        {* <!-- ******************** SEZNAM UDÁLOSTI (TIMELINE) ******************** --> *}
                        <div class="row events">
                            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                                <div class="row">

                                    {? $implementationName = 'udalost'; }
                                    {? $ssortedParams = array(); }

                                    {foreach $productsList as $product}
                                        {if isset($product->param[$implementationName]) && !empty($product->param[$implementationName])}
                                        
                                            {if is_array($product->param[$implementationName])}
                                                {? $params = $product->param[$implementationName]}
                                            {else}
                                                {? $params = array($product->param[$implementationName])}  {* produkt ma tento parametr pouze s jednou hodnotou (tzn nevraci to pole), tak si to pole vytvorime *}
                                            {/if}
                                        
                                            {foreach $params as $param}
                                                {if !array_key_exists($param->id, $ssortedParams)}
                                                    {? $ssortedParams[$param->id] = $param; }
                                                {/if}
                                            {/foreach}
                                        {/if}
                                    {/foreach}

                                    {foreach $ssortedParams as $param}
                                        <div class="col-xs-5 col-sm-5 col-md-5 col-lg-5 {if $iterator->getCounter()%2 == 0}to-right{else}to-left{/if} {if $iterator->getCounter() == 1}first{/if}">
                                            <div class="ev-box new">
                                                {if $iterator->getCounter()%2 == 0}
                                                    <div class="ev-arr-r"></div>
                                                {else}
                                                    <div class="ev-arr-l"></div>
                                                {/if}
                                                <img class="main" src="{plink Files:default $param->mainFoto,458,257,null,null,false,File::FILL}" alt="{$param->name}" title="{$param->name}" />
                                                <h3><a href="{plink Search:default array('udalost'=>$param->id)}">{$param->name}</a></h3>
                                                {!$param->describe|implode:', '}
                                            </div>  
                                        </div>
                                    {/foreach}

                                <!--     <div class="cold-md-5 ev-box u1">

                                        <img src="../images/ev-arr-l.jpg" class="ev-arr-l">
                                        <img src="" data-src="holder.js/440x200/text:událost" class="img-thumbnail img-responsive" />
                                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus blandit dui a mattis vestibulum. Mauris rhoncus magna id mauris euismod vehicula.</p>
                                    </div>
                                    <div class="cold-md-5 ev-box u2">
                                        <img src="../images/ev-arr-r.jpg" class="ev-arr-r">
                                        <img src="" data-src="holder.js/440x200/text:událost" class="img-thumbnail img-responsive" />
                                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus blandit dui a mattis vestibulum. Mauris rhoncus magna id mauris euismod vehicula.</p>
                                    </div>
                                    <div class="cold-md-5 ev-box u3">
                                        <img src="../images/ev-arr-l.jpg" class="ev-arr-l">
                                        <img src="" data-src="holder.js/440x200/text:událost" class="img-thumbnail img-responsive" />
                                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus blandit dui a mattis vestibulum. Mauris rhoncus magna id mauris euismod vehicula.</p>
                                    </div>
                                    <div class="cold-md-5 ev-box u4">
                                        <img src="../images/ev-arr-r.jpg" class="ev-arr-r">
                                        <img src="" data-src="holder.js/440x200/text:událost" class="img-thumbnail img-responsive" />
                                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus blandit dui a mattis vestibulum. Mauris rhoncus magna id mauris euismod vehicula.</p>
                                    </div>
                                </div>



                                <div class="row">
                                    {foreach $productsList as $product}
                                        {if isset($product->parameters)}
                                            {foreach $product->parameters as $param}
                                                {if isset($product->param[$param->implementationName]) && !empty($product->param[$param->implementationName])}
                                                    
                                                    {if $param->implementationName == 'udalost'}
                                                        {if is_array($product->param[$param->implementationName])}
                                                            <div class="col-xs-5 col-sm-5 col-md-5 col-lg-5 time-left">
                                                                {$product->param[$param->implementationName]|implode: ' '.$param->unit.', '}
                                                            </div>
                                                        {else}
                                                            <div class="col-xs-5 col-sm-5 col-md-5 col-lg-5 time-right">
                                                                {$product->param[$param->implementationName]}
                                                            </div>
                                                        {/if}
                                                        {if isset($param->unit)} {$param->unit}{/if}
                                                    {/if}
                                                {/if}
                                            {/foreach}
                                        {/if}
                                    {/foreach}
                                </div> --> 
                            </div>
                        </div> 
                            <div class="divider-big"></div>
                            {* <!-- ******************** SEZNAM VŠECH INTERPRETŮ  DLE ABECEDY ******************** --> *}
                            {? include(APP_DIR.'/templates/Functions/getCategoriesAlphabetically.php'); }
                            <div class="row">
                                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                                    <div class="alphabeticaly">
                                        {? 
                                            $iterArr = array_fill_keys($alphabet, 0);
                                            $myIter = array();

                                            
                                            $categoriesAlphabetically = getCategoriesAlphabetically($actualCategory);
                                            $lastUsedLetter = "";
                                        }
                                        <style>
                                            div.ln-column { width: 200px; float: left; }
                                        </style>

                                        {foreach $categoriesAlphabetically as $cat2}
                                            {?
                                                $firstLetter = strtolower(substr($cat2->name,0,1));
                                            }

                                            {if $lastUsedLetter != $firstLetter}
                                                {if $lastUsedLetter != ""}
                                                    </div> <!-- for previous ln-column 1 -->
                                                    </div> <!-- for previous ln-wrapper 1 -->
                                                {/if}
                                                <h3 id="{$firstLetter}">{? echo strtoupper($firstLetter)}</h3>
                                                <div class="ln-wrapper">
                                                {? $lastUsedLetter = $firstLetter}
                                            {/if}

                                            {if $iterArr[$firstLetter] == 0}
                                                <div class="ln-column">
                                            {/if}

                                            {if $iterArr[$firstLetter] > 0 && $iterArr[$firstLetter]%4==0}
                                                </div><div class="ln-column">
                                            {/if}

                                            <div class="ln-{? echo $firstLetter; }">
                                                <a title="{$cat2->name}" href="{plink Search: array('category'=>$cat2->id)}"><span>{!$cat2->name}</span></a>
                                            </div>
                                            {? $iterArr[$firstLetter]++; }
                                        {/foreach}

                                        </div> <!-- for previous ln-column 2 -->
                                        </div> <!-- for previous ln-wrapper 2 -->
                                    </div>
                                    <a class="anchor right">Nahoru</a>
                                </div>
                            </div>  
                            <script>
                                $(document).ready(function() {
                                    //
                                    $('.alphabet a.ac').livequery(function(){
                                        $(this).anchor({ speed: 800, anchor: $(this).data('href'), minus: 70});
                                    });
                                    //
                                    var str = 'ln-';

                                    $('.alphabeticaly h3').each(function(){
                                        var letter = ($(this).attr('id')).replace('#','');
                                        $('.alphabet .'+letter).addClass('ac');
                                    });
                                });
                            </script>
                        </div>
                    </div>  
                {else}
                    
                {/if}                      
            {/if}


            {* <!-- ******************** FILTR DLE PARAMETRU ******************** --> *}
            {if !isset($actualCategory)} {* is not set *}
                <div class="row products">
                    {* <!-- ******************** L - LEVY SLOUPEC (filtr) ******************** --> *}
                    {* <!-- __________________________________________________________________ --> *}
                    <div class="col-xs-2 col-sm-2 col-md-2 col-lg-2">
                        <div class="row">
                        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                            <h3>Filtr paremetrů</h3>
                            <hr class="divider-big line" />
                            {include ../Includes/filter.phtml limitersURL => $limitersURL}
                        </div>
                    </div>
                    </div>
                    {* <!-- ******************** R - PRAVY SLOUPEC (vypis kategorie) ******************** --> *}
                    {* <!-- _____________________________________________________________________________ --> *}
                    <div class="col-xs-10 col-sm-10 col-md-10 col-lg-10">
                    {*  {control breadcrumb}
                        {? $myCat = $actualCategory->id}
                        {? $cat = new Category($myCat);}
                       
                        {foreach $cat->galleries['foto'] as $gal}
                            {if $gal->implementation_name == 'logo'}
                            {foreach $gal->files as $file}        
                                <img src="{plink Files:default $file->id,150,80}" alt="{$product->name}" class="pull-right logo" />
                            {/foreach}
                            {/if}
                        {/foreach}
                        <div class="cat-description">

                            {? $myCat = $actualCategory->id}
                            {? $cat = new Category($myCat);}
                            
                            {foreach $cat->galleries['foto'] as $gal}  
                                {if $gal->implementation_name == 'uvodni'}
                                {foreach $gal->files as $file}        
                                    {if isset($file->url) && $file->url != '' }
                                        {if strpos('youtube', $file->url)}
                                            <object width="459" height="300">
                                                <param value="true" name="allowfullscreen" />
                                                <param value="always" name="allowscriptaccess" />
                                                <param name="movie" value="{$file->url|replace:'watch?v=':'v/'}?version=3&amp;hl=cs_CZ" />
                                                <param name="wmode" value="transparent" />
                                                <embed width="459" height="300" allowscriptaccess="always" 
                                                  allowfullscreen="true" type="application/x-shockwave-flash"          
                                                  src="{$file->url|replace:'watch?v=':'v/'}?version=3&amp;hl=cs_CZ"
                                                  wmode="transparent"
                                                  >
                                                </embed>
                                            </object>
                                        {else}
                                            no
                                        {/if}
                                    {else}
                                        <img src="{plink Files:default $file->id,459,300,null,null,false,File::FILL}" class="img-thumbnail pull-left" /> 
                                    {/if}
                                {/foreach}
                                {/if}
                            {/foreach} 
                            <h1>{if isset($actualCategory)}{$actualCategory->title}{else}{_'Výsledky vyhledávání'}{/if}</h1>
                            <div>{if isset($actualCategory)}{!$actualCategory->description}{/if}</div>
                            <hr class="clear" />
                        </div> *}
                        <h1>Limiter gender</h1>
                        {? var_dump($limiter);}  
                        <hr class="divider-sml">
                        
                        {* <!-- CO FRCI (slider) --> *}
                        {if isset($lists['co-frci']) && count($lists['co-frci'])>=5}                    
                                    <h2 class="endlessgal">Co právě frčí</h2>
                                    <div class="co-frci col-xs-12 col-sm-12 col-md-12 col-lg-12" id="frci"> 
                                        <ul class="row ul products-list">                                    
                                            {foreach $lists['co-frci'] as $product}
                                                <li class="col-xs-2 col-sm-2 col-md-2 col-lg-2 {if $iterator->getCounter()%5==0}last{/if}">
                                                    {include ../Includes/product-list.phtml product=>$product}
                                                </li>
                                            {/foreach}
                                        </ul>
                                    </div>
                                    <script>
                                        $('#frci').endlessGallery({ speed: 200, count: 1 });
                                        $('#out-frci').addClass('row');
                                    </script>
                            <div class="divider-big"></div>
                        {/if}<div class="divider-big"></div><div class="divider-big"></div>
                        <div id="ordererTabs"></div>
                        <div class="divider-big"></div>
                        
                        {* <!-- ******************** PRODUCT-LIST ******************** --> *}
                            <ul class="row" id="products-list">
                                {foreach $productsList as $product}    
                                    <li class="col-xs-2 col-sm-2 col-md-2 col-lg-2 {if $iterator->getCounter()%5==0}last{/if}">
                                        {include ../Includes/product-list.phtml product=>$product}
                                    </li>
                                {/foreach}
                            </ul>
                        {widget paginator}
                        <script>
                            $(window).on('scroll',function(){
                                if($(window).scrollTop() + $(window).height() > $(document).height() - 1000) {
                                    if ($('a.next').length>0){
                                        $('a.paginator-next-button').trigger('click');
                                    }
                                    else {
                                        $('#gal-wrap-note').fadeIn();
                                    }
                                }
                            });        
                        </script>                         

                        {* <!-- CO FRCI (slider) --> *}
                        {* <!-- <script>
                            $(window).scroll(function() {
                                if(isVisibleOnScreen($('#bott-list2'))) {
                                    $('#bott-list2').fadeIn();
                                }
                            });
                        </script> --> *}
                        <div class="row" id="gal-wrap-note">
                            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                                <h2>Co frčí hned</h2>
                                <div class="products-list co-frci" id="frci2"> 
                                    <ul class="row ul">                                    
                                        {foreach $lists['co-frci'] as $product}
                                            <li class="col-xs-2 col-sm-2 col-md-2 col-lg-2 {if $iterator->getCounter()%5==0}last{/if}">
                                                {include ../Includes/product-list.phtml product=>$product}
                                            </li>
                                        {/foreach}
                                    </ul>
                                </div>
                                <script>
                                    $('#frci2').endlessGallery({ speed: 200, count: 1 });
                                </script>
                                {*
                                    <div class="prev" ></div>
                                    <div class="next" ></div>
                                *}
                            </div>
                        </div>
                        <div class="divider-big"></div>
                        <a class="anchor">Nahoru</a>
                    </div>
                </div>
            {/if}
        </div>
    </div>
    <script>
        $(document).ready(function() {
            $('.anchor').anchor({ speed: 800, anchor:'body', minus: 0 });
            $('.anchor, .paginator a').livequery(function(){
                $(this).anchor({ speed: 800, anchor:'body', minus: 0});
            });
        });
    </script>
    <script>
        $('#ordererTabs').ordererTabs([ // protoze je tu latte (preklady)
            { name: {_'Nejprodávanější'} , lim: 'product_venality' , val: 'desc'},
            { name: {_'Největší sleva'} , lim: 'product_sale', val: 'desc'},
            { name: {_'Od nejlevnějšího'} , lim: 'product_price', val: 'asc'},
            { name: {_'Od nejdražšího'} , lim: 'product_price', val: 'desc'}
        ]);
    </script>
{/block}